apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: go-app
          image: peerasilp/7solution-app
          env:
            - name: APP_ENV
              value: "dev"
