apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: go-app
          image: peerasilp/7solution-app:v1.0.3
          env:
            - name: APP_ENV
              value: "prod"
