apiVersion: v1
kind: Service
metadata:
  name: {{ include "7solution-infra.fullname" . }}
  labels:
    app: {{ include "7solution-infra.name" . }}
    {{- include "7solution-infra.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "7solution-infra.name" . }}
    {{- include "7solution-infra.selectorLabels" . | nindent 4 }}